// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rknRallySlotApp.Datos;

#nullable disable

namespace rknRallySlotApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725050312_CorregirFKPrueba")]
    partial class CorregirFKPrueba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("rknRallySlotApp.Modelos.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaPuntuacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Coche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coches");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CocheId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dorsal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCoche")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPiloto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPrueba")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PilotoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PruebaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verificado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CocheId");

                    b.HasIndex("PilotoId");

                    b.HasIndex("PruebaId");

                    b.HasIndex("IdPrueba", "Dorsal")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abreviado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Escuderia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Palmares")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Abreviado")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Prueba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumEtapas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TiempoMaximo")
                        .HasColumnType("TEXT");

                    b.Property<int>("TramosPorEtapa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato", "Nombre")
                        .IsUnique();

                    b.ToTable("Pruebas");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.TiempoTramo", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etapa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tramo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdInscripcion", "Etapa", "Tramo");

                    b.HasIndex("InscripcionId");

                    b.ToTable("TiemposTramos");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Inscripcion", b =>
                {
                    b.HasOne("rknRallySlotApp.Modelos.Coche", "Coche")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CocheId");

                    b.HasOne("rknRallySlotApp.Modelos.Piloto", "Piloto")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PilotoId");

                    b.HasOne("rknRallySlotApp.Modelos.Prueba", "Prueba")
                        .WithMany("Inscripciones")
                        .HasForeignKey("PruebaId");

                    b.Navigation("Coche");

                    b.Navigation("Piloto");

                    b.Navigation("Prueba");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Prueba", b =>
                {
                    b.HasOne("rknRallySlotApp.Modelos.Campeonato", "Campeonato")
                        .WithMany("Pruebas")
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.TiempoTramo", b =>
                {
                    b.HasOne("rknRallySlotApp.Modelos.Inscripcion", "Inscripcion")
                        .WithMany("Tiempos")
                        .HasForeignKey("InscripcionId");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Campeonato", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Coche", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Inscripcion", b =>
                {
                    b.Navigation("Tiempos");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Piloto", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("rknRallySlotApp.Modelos.Prueba", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
